### ISSUE TITLE
Verification don't work

### ISSUE THREAD

**Issue by Daedra223** [wetterfroschdus/Jodel-Wetterfrosch#5]
Hast du eine Möglichkeit gefunden die Verifizierung durchzuführen, seit 3 Tagen bekommt man ja nur leere Responses, laut deiner Rückmeldung hängt es mit der Verifizierung zusammen. Aber selbst mit der Verifizierung die du beschrieben hast klappt es nicht ...

**Comment by wetterfroschdus** [comment]
rtfm ;)
Also that's a jodel_api thing.
